#FROM balenalib/%%BALENA_MACHINE_NAME%%
#FROM ubuntu:18.04
FROM raspbian/stretch

ENV INITSYSTEM on

RUN apt-get update && apt-get install -yq \
  python3 \
  python3-sense-hat \
  python3-influxdb \
  vim \
  wget && \
  apt-get clean && rm -rf /var/lib/apt/lists/*

COPY . /usr/src/app
WORKDIR /usr/src/app
RUN echo "dtoverlay=rpi-sense" >> /boot/config.txt
# NOTE: need to configure device variables in balena dashboard

# Finally, start our app
CMD ["python3", "/usr/src/app/measure.py"]
